---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PortfolioA35
  children:
  - name: BillingPortal-App
    type: udm.Application
    lastVersion: !format 1.0.%BUILD_NUMBER%
    children:
    - name: !format 1.0.%BUILD_NUMBER%
      type: udm.DeploymentPackage
      applicationDependencies:
        BillingPortal-Data: !format 1.0.%BUILD_NUMBER%
      deployables:
      - name: static-site-frontend-service
        type: k8s.ServiceSpec
        serviceName: static-site
        serviceType: ClusterIP
        selectors:
          application: static-site
        ports:
        - name: http
          type: k8s.ServicePortSpec
          portName: http
          port: "80"
      - name: static-site-frontend-pods
        type: k8s.DeploymentSpec
        containers:
        - name: caddy
          type: k8s.ContainerSpec
          containerName: caddy
          image: !format "%DEPLOYMENTREGISTRY%/billing-portal/static-site:1.0.%BUILD_NUMBER%"
        podCreateDeleteRetryCount: "20"
        labels:
          application: static-site
        restartPolicy: Always
        deploymentName: static-site
        replicasCount: "1"
      - name: api-backend-service
        type: k8s.ServiceSpec
        serviceName: api
        serviceType: ClusterIP
        selectors:
          application: api
        ports:
        - name: http
          type: k8s.ServicePortSpec
          portName: http
          port: "80"
      - name: api-backend-pods
        type: k8s.DeploymentSpec
        containers:
        - name: api
          type: k8s.ContainerSpec
          containerName: api
          image: !format "%DEPLOYMENTREGISTRY%/billing-portal/api:1.0.%BUILD_NUMBER%"
        podCreateDeleteRetryCount: "20"
        labels:
          application: api
        restartPolicy: Always
        deploymentName: api
        replicasCount: "1"
      - name: haproxy-service
        type: k8s.ServiceSpec
        serviceName: billing-portal
        serviceType: ClusterIP
        selectors:
          application: haproxy
        ports:
        - name: http
          type: k8s.ServicePortSpec
          portName: http
          port: "8082"
          targetPort: "80"
      - name: haproxy-pods
        type: k8s.DeploymentSpec
        containers:
        - name: haproxy
          type: k8s.ContainerSpec
          containerName: haproxy
          image: !format "%DEPLOYMENTREGISTRY%/billing-portal/haproxy:1.0.%BUILD_NUMBER%"
        podCreateDeleteRetryCount: "20"
        labels:
          application: haproxy
        restartPolicy: Always
        deploymentName: haproxy
        replicasCount: "1"
      - name: jboss-payments-module
        type: jbossdm.War
        contextRoot: "{{ CONTEXT_ROOT }}"
        file: !file "payments/payment-cdi-event/target/payment-cdi-event.war"
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PortfolioA35
  children:
  - name: BillingPortal-Data
    type: udm.Application
    lastVersion: !format 1.0.%BUILD_NUMBER%
    children:
    - name: !format 1.0.%BUILD_NUMBER%
      type: udm.DeploymentPackage
      deployables:
      - name: database-update-scripts
        type: sql.SqlScripts
        file: !file "sql/sql-scripts.zip"
---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PortfolioA35
  children:
  - name: BillingPortal-BlueGreen
    type: udm.Application
    lastVersion: !format 1.0.%BUILD_NUMBER%
    children:
    - name: !format 1.0.%BUILD_NUMBER%
      type: udm.DeploymentPackage
      deployables:
      - name: load-balancer-service
        type: k8s.ServiceSpec
        serviceName: billing-portal-loadbalancer
        serviceType: ClusterIP
        selectors:
          application: "{{ ACTIVE_ENVIRONMENT }}"
        ports:
        - name: http
          type: k8s.ServicePortSpec
          portName: http
          port: "8082"
          targetPort: "80"