languageCode = "en-us"
theme = "hugo-swift-theme"
title = "digital.ai"
canonifyurls = true
paginate = 4

[params]
    custom_css = ["css/styles.css"]
    designed_by = "Neal DeBuhr"
    copyright = "digital.ai"
    footer_content = "Powered by the Digital.ai Platform"
    headline = "Digital.ai Billing Service"
